# Generated by Django 4.1.4 on 2023-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('lenght', models.IntegerField(verbose_name='Продолжительность курса')),
                ('cost_individual', models.IntegerField(verbose_name='Стоимость индивидульного занятия')),
                ('cost_group', models.IntegerField(verbose_name='Стоимость группового занятия')),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('parents', models.CharField(max_length=250, verbose_name='Представитель')),
                ('phone', models.IntegerField(verbose_name='Контактный телефон')),
                ('is_group', models.BooleanField(default=False, verbose_name='Групповые занятия')),
            ],
        ),
    ]
