# Generated by Django 4.1.4 on 2023-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='pupil',
            name='is_individual',
            field=models.BooleanField(default=False, verbose_name='Индивидуальные занятия'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='parents',
            field=models.TextField(verbose_name='Представитель'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Контактный телефон'),
        ),
    ]
