# Generated by Django 4.1.4 on 2023-01-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_cours_options_alter_pupil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='lenght',
            field=models.IntegerField(blank=True, verbose_name='Продолжительность курса'),
        ),
    ]
