# Generated by Django 4.1.4 on 2023-01-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_cours_lenght'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='is_individual',
        ),
        migrations.AddField(
            model_name='pupil',
            name='education_form',
            field=models.CharField(choices=[('individual', 'индивидуальное'), ('group', 'групповое')], default='individual', max_length=50),
        ),
    ]
