# Generated by Django 4.1.4 on 2023-01-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_pupil_is_group_remove_pupil_is_individual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='cours',
            field=models.ManyToManyField(to='account.cours'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='education_form',
            field=models.CharField(choices=[('individual', 'индивидуальное'), ('group', 'групповое')], default='individual', max_length=50, verbose_name='Форма обучения'),
        ),
    ]
