# Generated by Django 4.1.4 on 2023-01-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_pupil_cours_alter_pupil_education_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='cours',
        ),
        migrations.AddField(
            model_name='pupil',
            name='age',
            field=models.CharField(max_length=3, null=True, verbose_name='Возраст'),
        ),
    ]
