# Generated by Django 4.1.4 on 2023-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_pupil_cours_pupil_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='course',
            field=models.ManyToManyField(to='account.cours'),
        ),
    ]
