# Generated by Django 4.1.4 on 2023-01-15 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0011_pupil_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='phone',
            field=models.IntegerField(verbose_name='Контактный телефон'),
        ),
    ]
