# Generated by Django 4.1.4 on 2023-01-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_cours_author_alter_cours_lenght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='cost_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость группового занятия'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cost_individual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость индивидульного занятия'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='lenght',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность курса, часов'),
        ),
    ]
