# Generated by Django 4.1.4 on 2023-01-16 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0019_alter_cours_author_alter_pupil_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cost_group',
            field=models.IntegerField(null=True, verbose_name='Стоимость группового занятия'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cost_individual',
            field=models.IntegerField(null=True, verbose_name='Стоимость индивидульного занятия'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='lenght',
            field=models.IntegerField(null=True, verbose_name='Продолжительность курса, часов'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
