# Generated by Django 4.1.4 on 2023-01-16 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_cours_author_alter_cours_cost_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.cours'),
        ),
    ]
