# Generated by Django 4.1.4 on 2023-01-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_alter_pupil_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='cost_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость группового занятия'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='cost_individual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость индивидульного занятия'),
        ),
    ]
